name: Create gigs

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install 11ty dependencies
        run: npm i markdown-it markdown-it-anchor

      - name: Create gigs 
        run: npx @gigsboat/cli

      - name: Copy file to eleventy starter directory
        run: cp README.md gigsboat-eleventy-starter/index.md

      - name: Set up and copy files to jekyll directory
        run: |
          mkdir -p jekyll/_layouts
          cp gigsboat-eleventy-starter/_includes/gigsboat-layout.liquid jekyll/_layouts/default.html
          (echo "---\nlayout: default\n---\n" && cat README.md) > index.md && mv index.md jekyll/index.md
          cp gigsboat-eleventy-starter/styles.css jekyll/styles.css

      - name: Create gigs html with 11ty
        run: npx @11ty/eleventy

      - name: Push gigs into repository
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          commit-message: 'chore: updating README with new gigs and create HTML'
          files: README.md docs/
          name: Liran Tal
          email: liran.tal@gmail.com
